### PR TITLE
The return of do_prom

### PR DESCRIPTION
**Pull request by katef**
I'd accidentally disabled the `-Wt,-N` flag for trans at some point. This PR returns it. It was already present in the manpage.

While I was here I saw that I'd removed a call to `make_extra_dec()` when `do_prom` (set by -N) is true. That was removed in b06dca2, where I evidently considered it unused code. Here I'm effectively reverting that removal.

From my commit:
> As far as I can tell, these calls just construct a dec struct, but don't actually use it. However this also invokes `add_prefix()` and `init_NAME()`, and essentially I just don't believe
so much code can be unused.

Now compiling a simple hello world with `-Wt,-N` gives:
```
/tmp/tcc-MX19JN1NJ6/_tcc.s: Assembler messages:
/tmp/tcc-MX19JN1NJ6/_tcc.s:28: Error: bad or irreducible absolute expression
/tmp/tcc-MX19JN1NJ6/_tcc.s:28: Error: junk at end of line, first unrecognized character is `,'
/tmp/tcc-MX19JN1NJ6/_tcc.s:29: Error: bad or irreducible absolute expression
/tmp/tcc-MX19JN1NJ6/_tcc.s:29: Error: junk at end of line, first unrecognized character is `,'
```
which seems to be caused by the `.bss` directives here:
```
.align 4
.size main, .-main
.bss .L0, 12
.bss .L1, 8
.section .rodata
.align 4
.L2:
.byte 104, 101, 108, 108, 111, 32, 37, 115, 10, 0
```
Perhaps these are unrelated, and need porting to GAS's dialect? I'm not sure. The syntax looks correct per the documentation for Sun's as(1) at least.

### CODE REVIEW

**Comment by katef** [comment]
With emitting `.lcomm` instead of `.bss`, GAS now happily assembles this and produces a binary. My binary runs, but does not print out hello world.

Looking at the generated assembly:
```
; cat hello.c 
#include <stdio.h>
int main(void) { printf("hello %s\n", "world"); return 0; }
; bmake -r CC=gcc TARGETARCH=x32_64 && ./obj.when-bootstrap/bin/tcc -Wt,-N -S hello.c
```
gives:
```!asm
.text
.type main,@function
.globl main
.align 4
main:
.set .Ldisp4, 0  
​    pushl $.L1
    pushl $.L0
    call printf
    pop %edx
    pop %edx
    xorl %eax,%eax
​    ret

.align 4
.size main, .-main
.lcomm .L0, 12
.lcomm .L1, 8
.section .rodata
.align 4
.L2:
.byte 104, 101, 108, 108, 111, 32, 37, 115, 10, 0

.section .rodata
...

.align 4
.L3:
.byte 119, 111, 114, 108, 100, 0
​
.text
.type __I.TDFmainSunAug231804102020,@function
.globl __I.TDFmainSunAug231804102020
.align 4
__I.TDFmainSunAug231804102020:
.set .Ldisp6, 0
...
```
(courtesy of help from @iximeow, thank you):
> where it looks like they're expected to be initialized in __I.TDFmainSunAug231804102020, but nothing would call that
> that function just copies from L2 and L3 to L0 and L1
> by default they'll be the empty string which would be why you see nothing printed

So I expect we're missing emitting a call to initialise stuff.

**Comment by katef** [comment]
grepping around for `__I.TDF` (because it looks easy to spot), I see exactly our missing call in /trans/src/x86/translate.c:
```!c
             if (dyn_init && strncmp("__I.TDF", name + strlen(name_prefix), 7) == 0) {
                 out_initialiser(name);
                 set_proc_uses_external (child (tag));   /* for PIC_code, should be done in install_fns? */
             }
```
So `dyn_init` must be false, when it should be true. Here's the equivalent code from the pre-kate 4.1.2 release:
```!c
     if (name (son (tg)) == proc_tag || name (son (tg)) == general_proc_tag) {
       if (strncmp("__I.TDF", id+prefix_length, 7)==0) {
```
So it seems I added `dyn_init` at some point, and missed a situation for setting it.

Grepping again, I see /trans/src/common/main/flags.c presents a -Y flag. So I can test this by setting it by hand:
```
; bmake -r CC=gcc TARGETARCH=x32_64 && ./obj.when-bootstrap/bin/tcc -Wt,-N -Wt,-Y hello.c && ./a.out
hello world
```
and running with tcc -S now shows the call we expect:
```!asm
.section .init
    call __I.TDFmainSunAug231904022020
```

**Comment by katef** [comment]
And indeed I see the -Y flag is set for the systems which needed it:
```
; grep -r -- -Y osdep | grep FLAG_TRANS
osdep/machines/irix/mips/env/common/default:>FLAG_TRANS		"-S -D1 -Y"
osdep/machines/hpux/common/env/default:>FLAG_TRANS	"-Y"
osdep/machines/solaris/x86_32/env/default:>FLAG_TRANS		"-Y"
osdep/machines/sunos/sparc/env/default:+FLAG_TRANS		"-b -Y -n"
osdep/machines/sunos/m68k/env/default:>FLAG_TRANS		"-Y"
osdep/toolchain/aix/common/default:>FLAG_TRANS		"-Y"
```

So I could also add `-Y` for x86 on Linux, too. But I don't think I want to do that, because it's only needed there for PROM code. So instead I'm going to set `dyn_init` automatically when `do_prom` is true.

**Comment by katef** [comment]
And with this, my hello world when only do_prom is set (by passing the -N flag to trans):
```
; bmake -r CC=gcc TARGETARCH=x32_64 && ./obj.when-bootstrap/bin/tcc -Wt,-N hello.c && ./a.out
hello world
```

**Comment by katef** [comment]
Good job Kate.
Thank you @iximeow!

**Comment by katef** [comment]
Glossary:

"trans" stands for translator. That's the program that translates an internal representation to assembly

`do_prom`: According to the [trans(1) manpage for -N](http://www.tendra.org/trans.1/#arg-N), this is to "Produce PROM code (avoiding `.data`).". I don't really know what that means, but that's fine. We can make it work anyway.

**Comment by goldibex** [comment]
Hi @katef! I think `Produce PROM code (avoiding .data)` probably means that the target architecture for the compiled and linked object code only has read-only storage (i.e. a PROM), and therefore use of the `.data` segment, which is read-write, should be avoided.

**Comment by goldibex** [comment]
Having now examined the translator sources, I think this is exactly the meaning of `-N` -- it refuses to emit a `.data` segment if the code is being compiled for a target where a `.data` segment is impossible.

**Pull request merged**
