### PR TITLE
Avoid calling exit from an atexit callback

### PR DESCRIPTION
**Pull request by pascal-cuoq**
Fixes https://github.com/tendra/tendra/issues/40

I chose to call `_Exit` because it is part of C99. It is also possible to call `_exit` (the POSIX name for the same function); in fact `tcc/src/main.c` already does `#include <unistd.h>` (the POSIX header that provides `_exit` and that would have to be included in `error.c` in order to call `_exit` in that file). But in 2020, depending on a C99 function seems the least constraining requirement.

I made the variable `exiting` an `int` in case using `_Bool` would complicate TenDRA's bootstrap. It should be a `_Bool`.

### CODE REVIEW

**Comment by katef** [comment]
Ah thank you for this!

> But in 2020, depending on a C99 function seems the least constraining requirement.

So we might think! Your reasoning makes sense, and in any other codebase, I would agree.

We have a second phase after bootstrap (`make bootstrap-rebuild`) which rebuilds using TenDRA itself. And we only have a WIP implementation for C99, so far. Currently the rebuild is all C90. Unfortunately that will fail here.

We do depend on posix already (as you saw), so would be fine to use `_exit()` instead.
And you can see in /tcc/src/Makefile that we set `TCCOPTS= -Yposix` which allows use of the POSIX API. And indeed `_exit()` is provided for the API spec there:
```
; grep -r _exit tspec/base
tspec/base/posix/posix/unistd.h.ts:    +FUNC ~bottom _exit ( int ) ;
```

**Comment by pascal-cuoq** [comment]
Understood, I have added a commit that replaces the call to `_Exit` by a call to `_exit`. The commits should be squashed into one at merge-time if GitHub allows to do this conveniently.

**Comment by pascal-cuoq** [comment]
If making `shared/src/error.c` depend on posix is not palatable, there is a third possibility, which is to call `abort()`. The function `abort()` does not pass control to the callbacks installed with `atexit()`, it is specified as part of C90, and `git grep` shows that it is already used in `shared/src/error.c`. The only loss of functionality in this case is that when an error happens in an `atexit` callback, the executable will return the termination status hard-coded by the host implementation for `abort()` instead of the one desired by the executable. This seems minor, and is still an improvement over the infinite recursion that currently happens in this case of some OSes.

**Comment by katef** [comment]
That makes sense, I'd forgotten that this is under shared/.

I agree, it would be nice to avoid bringing in posix for everything there. `abort()` is a good idea, but I think it gives a bit more of a brutal termination than we really want here (from a user's perspective). I vote we stick with `_exit()`. What a bother!

I wish we could avoid calling `error()` from within an atexit handler in the first plae. I think that's probably infeasible for tcc, though.

Anyway to test this I think we need a system where bootstrap-rebuild runs (not Linux at the moment), and to set `TCCOPTS= -Yposix` in whichever makefiles are appropriate for the new dependency. I can test this on FreeBSD/i386 if you like.

**Comment by pascal-cuoq** [comment]
I can only test either the same kind of platform as Continuous Integration (various versions of Ubuntu on x86-64) or the C platform on which I noticed the problem, which is not even close to allowing TenDRA to bootstrap (more on that later), so any tests that you could do on platforms that seem relevant would be very useful.

**Comment by katef** [comment]
In #58 I split up the -Yposix flags per file, rather than per project. Your PR here does introduce a new file that now depends on POSIX, where it didn't previously (and I just confirmed this by testing the rebuild on FreeBSD). So we'll need to add `TCCOPTS.error.c += -Yposix` for this file too.

I'll merge your PR first, and add that myself directly on main, because I think it's a little unfair to ask you to add something that you can't test yourself.

Sorry it took me a few days to be able to test it (and write #58). Thank you for the good work!

**Comment by katef** [comment]
Added -Yposix for error.c in 2087a9eab, and with that bootstrap-rebuild passes on FreeBSD for the new dependency there.

I suppose I probably should've done that on a merge commit, but this way seemed simpler.

Thank you again!

**Pull request merged**
